### ISSUE TITLE
Problem with Proposal Layer

### ISSUE THREAD

**Issue by AlishaRege** [rbgirshick/py-faster-rcnn#219]
Hi,
I am having trouble figuring out how to fix the following problem. 

Traceback (most recent call last):
  File "./tools/demo.py", line 135, in <module>
    net = caffe.Net(prototxt, caffemodel, caffe.TEST)
  File "/home/ubuntu/merge/new/py-faster-rcnn/tools/../lib/rpn/proposal_lay
    print "\n\n", self.param_str_,"\n\n"
AttributeError: 'ProposalLayer' object has no attribute 'param_str_'

the proposal_layer file is in rpn.

**Comment by Austriker** [comment]
Which version of caffe are you using. In the latest caffe 'param_str_' is not implemented this way in the python layer.

**Comment by karaspd** [comment]
Hi,
I've got the same error, and I am using the latest version of caffe. Does anyone know how can I solve the issue without downgrading caffe?

**Comment by Austriker** [comment]
@amrege @karaspd I solved this problem by forking the project [py-faster-rcnn](https://github.com/Austriker/py-faster-rcnn).

It works with python 3 and should work with python 2 but i haven't tested it

**Comment by karaspd** [comment]
Thank you @amrege I fixed it by modifying param_str_ to param_str . (in latest version of caffe it was defined param_str)

**Comment by wuyuzaizai** [comment]
@karaspd, hi , i have the same problem, and i modified param_str_ to param_str only in proposal_layer.py, it doesn't work, please do me a favor

**Comment by pchankh** [comment]
@karaspd , hi I have the same problem with wuyuzaizai. I am still having the problem despite doing the change of param_str_ to param_str in lib/rpn/proposal_layer.py

I1225 15:12:20.765244 2063896576 net.cpp:408] proposal -> rois
Traceback (most recent call last):
  File "./tools/demo.py", line 135, in <module>
    net = caffe.Net(prototxt, caffemodel, caffe.TEST)
AttributeError: can't set attribute

Appreciate if anyone can help with the fix.

**Comment by karaspd** [comment]
@pchankh and @wuyuzaizai  Hi, I do not have my codes right now. But, I guess probably param_str_  might be used in another files as well. You can check it with ack-grep, if you are working with linux machine.  sudo  apt-get install ack-grep. Then find in which other files param_str_ presents.

**Comment by kirk86** [comment]
@karaspd I think those are the files...
py-faster-rcnn/lib/rpn/anchor_target_layer.py:        layer_params = yaml.load(self.param_str_)
py-faster-rcnn/lib/rpn/proposal_layer.py:        layer_params = yaml.load(self.param_str_)
py-faster-rcnn/lib/rpn/proposal_target_layer.py:        layer_params = yaml.load(self.param_str_)
py-faster-rcnn/lib/roi_data_layer/layer.py:        layer_params = yaml.load(self.param_str_)

**Comment by saranaws07** [comment]
@karaspd After making changes in all mentioned files, I am getting below error. Please help.
Loaded network /home/ubuntu/FRCN_ROOT/data/faster_rcnn_models/VGG16_faster_rcnn_final.caffemodel
Traceback (most recent call last):
  File "./tools/demo.py", line 142, in <module>
    _, _= im_detect(net, im)
  File "/home/ubuntu/FRCN_ROOT/tools/../lib/fast_rcnn/test.py", line 154, in im_detect
    blobs_out = net.forward(**forward_kwargs)
  File "/home/ubuntu/FRCN_ROOT/tools/../caffe-fast-rcnn/python/caffe/pycaffe.py", line 121, in _Net_forward
    self._forward(start_ind, end_ind)
  File "/home/ubuntu/FRCN_ROOT/tools/../lib/rpn/proposal_layer.py", line 65, in forward
    pre_nms_topN  = cfg[cfg_key].RPN_PRE_NMS_TOP_N
KeyError: '1'

**Comment by saranaws07** [comment]
I updated below two files also. I used ack-grep for search param_str_.
/home/ubuntu/FRCN_ROOT/caffe-fast-rcnn/.build_release/src/caffe/proto/caffe.pb.h
/home/ubuntu/FRCN_ROOT/caffe-fast-rcnn/.build_release/src/caffe/proto/caffe.pb.cc

but no success.

**Comment by smfullman** [comment]
@saranaws07 I was running into similar issues with CUDA 8.0 and cuDNN 5.1 and followed the instructions in [this comment in issue 237](https://github.com/rbgirshick/py-faster-rcnn/issues/237#issuecomment-230486523) by @manipopopo.  From there I was getting the same KeyError: '1' problem, and realized that cfg_key was not getting set to TRAIN or TEST in self.phase.  If you just want to run the demo, you can change it in proposal_layer.py manually:
<pre>
#cfg_key = str(self.phase) # either 'TRAIN' or 'TEST'
cfg_key = 'TEST'
</pre>
That worked fine for me in terms of executing the demo script, however it will break when you try and train a new model. Still investigating how to fix it permanently.

**Comment by mdadhich** [comment]
@smfullman Can you please tell us which file has this cfg_key ??
Thanks

**Comment by smfullman** [comment]
@mdadhich yes, that was changed in the lib/rpn/proposal_layer.py file on line 64 in the master branch.

**Comment by mdadhich** [comment]
I tried this, it didn't work for me, @smfullman, I have given full description of my problem https://github.com/rbgirshick/py-faster-rcnn/issues/494, have a look, if you have any other suggestion.

**Comment by happynear** [comment]
@smfullman , @mdadhich ,

The phase in Caffe is no longer string 'TRAIN' or 'TEST'. It is 0(TRAIN) or 1(TEST) now.

So just modify 
```
cfg_key = str(self.phase)
```
to
```
cfg_key = 'TEST' if self.phase == 1 else 'TRAIN'
```
can solve this issue.

**Comment by liceHuang** [comment]
> @karaspd After making changes in all mentioned files, I am getting below error. Please help.
> Loaded network /home/ubuntu/FRCN_ROOT/data/faster_rcnn_models/VGG16_faster_rcnn_final.caffemodel
> Traceback (most recent call last):
> File "./tools/demo.py", line 142, in 
> _, _= im_detect(net, im)
> File "/home/ubuntu/FRCN_ROOT/tools/../lib/fast_rcnn/test.py", line 154, in im_detect
> blobs_out = net.forward(**forward_kwargs)
> File "/home/ubuntu/FRCN_ROOT/tools/../caffe-fast-rcnn/python/caffe/pycaffe.py", line 121, in _Net_forward
> self._forward(start_ind, end_ind)
> File "/home/ubuntu/FRCN_ROOT/tools/../lib/rpn/proposal_layer.py", line 65, in forward
> pre_nms_topN = cfg[cfg_key].RPN_PRE_NMS_TOP_N
> KeyError: '1'

if you just want to run the domo,try to modify the file proposal_layer.py in line 65 to line 68 like this:
change
        pre_nms_topN  = cfg[cfg_key].RPN_PRE_NMS_TOP_N
        post_nms_topN = cfg[cfg_key].RPN_POST_NMS_TOP_N
        nms_thresh    = cfg[cfg_key].RPN_NMS_THRESH
        min_size      = cfg[cfg_key].RPN_MIN_SIZE
to
        pre_nms_topN  = 6000
        post_nms_topN = 300
        nms_thresh    = 0.7
        min_size      = 16

**Comment by liceHuang** [comment]
I sovle this problem by the follow steps:
1、use this https://github.com/intel/caffe/blob/master/src/caffe/layers/smooth_L1_loss_layer.cpp replace the local caffe project file caffe-master/src/caffe/layers/smooth_l1_loss_layer.cpp
2、rebuild caffe
3、copy all content in caffe-master/Build/x64/Release/pycaffe (include file classify.py, detect.py,draw_net.py and folder caffe) to both py-faster-rcnn-master\caffe-fast-rcnn\python and Anaconda3\envs\py27\Lib\site-packages
then it works.
I have tried some other implements of smooth_l1_loss_layer.cpp can not worl,finally this work.

**Comment by whuhxb** [comment]
> [@karaspd](https://github.com/karaspd) After making changes in all mentioned files, I am getting below error. Please help. Loaded network /home/ubuntu/FRCN_ROOT/data/faster_rcnn_models/VGG16_faster_rcnn_final.caffemodel Traceback (most recent call last): File "./tools/demo.py", line 142, in _, _= im_detect(net, im) File "/home/ubuntu/FRCN_ROOT/tools/../lib/fast_rcnn/test.py", line 154, in im_detect blobs_out = net.forward(**forward_kwargs) File "/home/ubuntu/FRCN_ROOT/tools/../caffe-fast-rcnn/python/caffe/pycaffe.py", line 121, in _Net_forward self._forward(start_ind, end_ind) File "/home/ubuntu/FRCN_ROOT/tools/../lib/rpn/proposal_layer.py", line 65, in forward pre_nms_topN = cfg[cfg_key].RPN_PRE_NMS_TOP_N KeyError: '1'

How to solve this problem?
