### ISSUE TITLE
Stuck at self.solver.step(1)

### ISSUE THREAD

**Issue by simonxmlee** [rbgirshick/py-faster-rcnn#428]
Hi,

    I try to train a ZF model with 2 class. I can train this model at one of my work station, but the train process get stuck at other work station. After I add logs to trace the reason, I find it would be stuck at self.solver.step(1). Does someone has related experience for this problem?

lib/fast-rcnn/train.py
---------------------------------------------------------------------------------------------------
def train_model(self, max_iters):
        ...
        while self.solver.iter < max_iters:
            # Make one SGD update
            timer.tic()
            self.solver.step(1)
            timer.toc() 
            ...

**Comment by ljd16** [comment]
@simonxmlee Did you solve this problem?

**Comment by simonxmlee** [comment]
@ljd16 Yes, it was resolved long time ago. I just remember the solution is related to configuration in proto.txt.

**Comment by fragrant8023** [comment]
@ljd16 hello, have you solved this problem? I meet this error and I do not know how to solve it .

**Comment by ljd16** [comment]
@fragrant8023 I have not solved this problem yet, but when I commented the use of cudnn, the error disappeared.
```
# cuDNN acceleration switch (uncomment to build with cuDNN).
# USE_CUDNN := 1
```

**Comment by Dshinji137** [comment]
@simonxmlee, Hello, I met the same situation now. Do you mean to adjust the parameters like base_lr or stepsize?

**Comment by simonxmlee** [comment]
@Dshinji137 Sorry, because this problem has resolved for a long time, I cannot remember the parameters which I edited. Maybe it is related to your class number which you want to classify.

**Comment by thisisdevanshu** [comment]
@Dshinji137  Were you able to resolve the issue?
