### ISSUE TITLE
I got the error when running demo.py

### ISSUE THREAD

**Issue by jojotata** [rbgirshick/py-faster-rcnn#8]
Hi.
I already successfully run fast-rcnn code written by the same author of this.
Then, I would like to try to use faster-rcnn..
However, when I run demo.py, I got this error.
'''
Traceback (most recent call last):
  File "./demo.py", line 18, in <module>
    from fast_rcnn.test import im_detect
  File ".../py-faster-rcnn-master/tools/../lib/fast_rcnn/test.py", line 17, in <module>
    from fast_rcnn.nms_wrapper import nms
  File ".../py-faster-rcnn-master/tools/../lib/fast_rcnn/nms_wrapper.py", line 11, in <module>
    from nms.gpu_nms import gpu_nms
ImportError: No module named gpu_nms
'''
Anyone has any idea about this  error?
Thank you.

**Comment by rbgirshick** [comment]
Did you run `make` in the `lib` directory?

**Comment by jojotata** [comment]
Oh, I'm sorry.
I haven't run "make" yet.

I really enjoy using your 'fast-rcnn'.
My ultimate goal is to run 'fast-rcnn' or 'faster-rcnn' with pretrained ImageNet model.
So, perheps I may ask some questions again.
Thank you.

**Comment by desaipratik1991** [comment]
Hi,
 when I run faster-rcnn demo.py, I got this error.
r\tools\..\lib\fast_rcnn\nms_wrapper.py", line 9, in <module>
    from nms.gpu_nms import gpu_nms
ImportError: No module named gpu_nms

I already run python setup.py file (Lib folder)

without using Make file is there any problem with that??

**Comment by ynpoornima** [comment]
I'm also facing the same issue even though I have done make already. Please help

**Comment by joyivan** [comment]
I faced the same problem too ?anyone solved it ?

**Comment by joyivan** [comment]
Traceback (most recent call last):
  File "test_net.py", line 13, in <module>
    from fast_rcnn.test import test_net
  File "/home/joyian/py-faster-rcnn/tools/../lib/fast_rcnn/test.py", line 17, in <module>
    from fast_rcnn.nms_wrapper import nms
  File "/home/joyian/py-faster-rcnn/tools/../lib/fast_rcnn/nms_wrapper.py", line 9, in <module>
    from nms.gpu_nms import gpu_nms
ImportError: No module named gpu_nms

**Comment by Deshna** [comment]
I am facing the same error while trying to use RCNN in CPU-only mode.

I fixed it by going to /FRCNN/py-faster-rcnn/lib/fast_rcnn/nms_wrapper.py and changing the code as follows:
from fast_rcnn.config import cfg
#from nms.gpu_nms import gpu_nms
from nms.cpu_nms import cpu_nms

def nms(dets, thresh, force_cpu=False):
    """Dispatch to either CPU or GPU NMS implementations."""

    if dets.shape[0] == 0:
        return []
    #if cfg.USE_GPU_NMS and not force_cpu:
    #    return gpu_nms(dets, thresh, device_id=cfg.GPU_ID)
    else:
        return cpu_nms(dets, thresh)

Commented out GPU-specific lines.

**Comment by plopd** [comment]
This holds also for [py-R-FCN](https://github.com/Orpine/py-R-FCN) if run in CPU mode.

**Comment by PetreanuAndi** [comment]
So GPU mode is still not solved? I want to run on GPU, but can't go over the "ImportError: No module named nms.gpu_nms " I have run make all over, and i think my caffe has all the paths set right (python and all) because it builds right. :(

**Comment by hadi-ghnd** [comment]
same here for gpu. Is there any solution?

**Comment by janaka1984** [comment]
how can detect multiple object on same image using demo.py ????????????

**Comment by R3v0lut10nist** [comment]
What does this error mean?

Traceback (most recent call last):
 File "./tools/demo.py", line 18, in <module>
    from fast_rcnn.test import im_detect
  File "/home/alakh/py-faster-rcnn/tools/../lib/fast_rcnn/test.py", line 17, in <module>
    from fast_rcnn.nms_wrapper import nms
  File "/home/alakh/py-faster-rcnn/tools/../lib/fast_rcnn/nms_wrapper.py", line 9, in <module>
    from nms.gpu_nms import gpu_nms
  File "__init__.pxd", line 155, in init nms.gpu_nms (nms/gpu_nms.cpp:4809)
ValueError: numpy.dtype has the wrong size, try recompiling. Expected 88, got 96

**Comment by will7200** [comment]
The issue most likely is that the setup.py file did not locate your cuda directory, so make sure that CUDAHOME env variable is pointing to the right directory, and make again.

**Comment by fujingling** [comment]
I face the error " image not found",anyone knows how to solve it. thanks!
the detail error as follows:
zhongzunfadeMacBook-Air:tools zhongzunfa$ python demo.py
Traceback (most recent call last):
  File "demo.py", line 17, in <module>
    from fast_rcnn.test import im_detect
  File "/Users/zhongzunfa/fjl/py-faster-rcnn/tools/../lib/fast_rcnn/test.py", line 16, in <module>
    import caffe
  File "/Users/zhongzunfa/fjl/py-faster-rcnn/tools/../caffe-fast-rcnn/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver
  File "/Users/zhongzunfa/fjl/py-faster-rcnn/tools/../caffe-fast-rcnn/python/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: dlopen(/Users/zhongzunfa/fjl/py-faster-rcnn/tools/../caffe-fast-rcnn/python/caffe/_caffe.so, 2): Library not loaded: libcaffe.so.1.0.0-rc3
  Referenced from: /Users/zhongzunfa/fjl/py-faster-rcnn/caffe-fast-rcnn/python/caffe/_caffe.so
  Reason: image not found

**Comment by ghost** [comment]
@deshanadesai : or a cleaner solution when the folloxing problem occurs: 'ImportError: No module named gpu_nms'

```
from fast_rcnn.config import cfg
if cfg.USE_GPU_NMS:
        from nms.gpu_nms import gpu_nms
from nms.cpu_nms import cpu_nms
```

**Comment by thezida** [comment]
Anyone solved the problem yet?

**Comment by christosavg** [comment]
So nothing newer on this issue yet, right?
Well, I've commented out both cpu and gpu nms lines and as expected, the results I was expecting were terrible. Still no clue what is this issue though.

**Comment by msha096** [comment]
try this 
import pyximport
pyximport.install()

**Comment by wangxing1212** [comment]
> try this
> import pyximport
> pyximport.install()

**Comment by wangxing1212** [comment]
@msha096 
I tried your method, but there was a mistake.

**Comment by wangxing1212** [comment]
@msha096 
I tried your method, but there was a mistake.
"CompileError: command 'gcc' failed with exit status 1\n"

**Comment by msha096** [comment]
Did you make successfully? and what is your gcc and cuda version?

**Comment by wangxing1212** [comment]
@msha096 cuda:8.0,gcc:4.9.3,I succeeded in another way.

**Comment by Chida15** [comment]
> @msha096 cuda:8.0,gcc:4.9.3,I succeeded in another way.

How do you deal with it? I also face the problem!

**Comment by wangxing1212** [comment]
@Chida15 You can switch to the Lib file, make

**Comment by 3bood86** [comment]
hello all
thanks for the great efforts

i am beginner in this field and i want to run the code

when i ran it i got this error

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-ef30beed4e34> in <module>
      1 import _init_paths
      2 import tensorflow as tf
----> 3 from fast_rcnn.config import cfg
      4 from fast_rcnn.test import im_detect
      5 from fast_rcnn.nms_wrapper import nms

ModuleNotFoundError: No module named 'fast_rcnn'

what should i do to fix it,
and where i can get the right steps?

**Comment by khan958** [comment]
Same Problem with 
ModuleNotFoundError: No module named 'nms.cpu_nms' 

Any one who have solved this problem yet?

**Comment by ignvinay** [comment]
I am also facing same issue : 
(tf_gpu) C:\Projects\new_caffe_fasterRCNN\py-faster-rcnn>python tools\demo.py
Traceback (most recent call last):
  File "tools\demo.py", line 18, in <module>
    from fast_rcnn.test import im_detect
  File "C:\Projects\new_caffe_fasterRCNN\py-faster-rcnn\tools\..\lib\fast_rcnn\test.py", line 17, in <module>
    from fast_rcnn.nms_wrapper import nms
  File "C:\Projects\new_caffe_fasterRCNN\py-faster-rcnn\tools\..\lib\fast_rcnn\nms_wrapper.py", line 10, in <module>
    from nms.cpu_nms import cpu_nms
ImportError: DLL load failed: The specified module could not be found.

**Comment by zhou3968322** [comment]
please use python 3.7.5, 3.7.4 python gpu_nms run failed.

**Comment by atursams** [comment]
I'm having the same problem :D
```
File "/root/plasticbag-faster-rcnn/tools/../lib/model/nms_wrapper.py", line 12, in <module>
from nms.gpu_nms import gpu_nms
ImportError: No module named gpu_nms
```

This is what my nms folder looks like:
```
ls lib/nms
__init__.py  __init__.pyc  cpu_nms.c  cpu_nms.cpython-35m-x86_64-linux-gnu.so  cpu_nms.pyx  gpu_nms.cpp  gpu_nms.cpython-35m-x86_64-linux-gnu.so  gpu_nms.hpp  gpu_nms.pyx  nms_kernel.cu  py_cpu_nms.py
```
